# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zIUc_XUP09CjrhM4gtAsJnDTlk7gceW7
"""

!pip install PyPDF2

!pip install python-docx

from PyPDF2 import PdfReader
from deep_translator import GoogleTranslator
import docx

#get book from the pdf file
reader = PdfReader('/home/justfortoday_med_book.pdf')
pages = reader.pages
book = []

for page in pages:
    book.append(page.extract_text())

#set the translator

translator = GoogleTranslator(source='en', target='es')

#translate the book and store it in a list
translatedBook = []
for page in book:
    translatedBook.append(translator.translate(page))

document = docx.Document()

for page in translatedBook:
    document.add_paragraph().add_run(page)
    document.add_page_break()

document.save("libroTraducido.docx")

